export const styles = {
  pageWrapper: {
    minHeight: "100vh",
    background:
      "linear-gradient(135deg, #1e3a8a 0%, #3b82f6 50%, #8b5cf6 100%)",
    padding: "40px 20px",
    position: "relative",
    overflow: "hidden",
  },
  animatedBg: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: `
      radial-gradient(circle at 10% 20%, rgba(59, 130, 246, 0.3), transparent 40%),
      radial-gradient(circle at 90% 80%, rgba(139, 92, 246, 0.3), transparent 40%),
      radial-gradient(circle at 50% 50%, rgba(30, 58, 138, 0.2), transparent 50%)
    `,
    animation: "float 20s ease-in-out infinite",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    position: "relative",
    zIndex: 1,
  },
  header: {
    textAlign: "center",
    marginBottom: "40px",
    animation: "fadeInDown 0.6s ease-out",
  },
  headerTitle: {
    fontSize: "clamp(2rem, 4vw, 3rem)",
    fontWeight: "800",
    color: "white",
    marginBottom: "10px",
    textShadow: "0 4px 20px rgba(0,0,0,0.3)",
  },
  headerSubtitle: {
    fontSize: "clamp(0.95rem, 2vw, 1.1rem)",
    color: "rgba(255,255,255,0.85)",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(320px, 1fr))",
    gap: "30px",
  },
  card: {
    background: "rgba(255,255,255,0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: "24px",
    padding: "35px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.25)",
    animation: "fadeInUp 0.8s ease-out",
    border: "1px solid rgba(255,255,255,0.3)",
  },
  profileCard: {
    background:
      "linear-gradient(135deg, rgba(59, 130, 246, 0.1), rgba(139, 92, 246, 0.1))",
    backdropFilter: "blur(20px)",
    borderRadius: "24px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.25)",
    animation: "fadeInUp 0.8s ease-out",
    border: "1px solid rgba(255,255,255,0.4)",
    textAlign: "center",
  },
  avatarWrapper: {
    width: "120px",
    height: "120px",
    margin: "0 auto 20px",
    borderRadius: "50%",
    background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    boxShadow: "0 10px 30px rgba(59, 130, 246, 0.4)",
    position: "relative",
  },
  avatarIcon: {
    width: "60px",
    height: "60px",
    color: "white",
  },
  onlineBadge: {
    position: "absolute",
    bottom: "8px",
    right: "8px",
    width: "24px",
    height: "24px",
    background: "#10b981",
    border: "3px solid white",
    borderRadius: "50%",
    boxShadow: "0 2px 10px rgba(16, 185, 129, 0.5)",
  },
  userName: {
    fontSize: "1.75rem",
    fontWeight: "700",
    color: "white",
    marginBottom: "8px",
    textShadow: "0 2px 10px rgba(0,0,0,0.2)",
  },
  userEmail: {
    fontSize: "1rem",
    color: "rgba(255,255,255,0.9)",
    marginBottom: "5px",
  },
  userBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    padding: "6px 14px",
    background: "rgba(255,255,255,0.25)",
    backdropFilter: "blur(10px)",
    borderRadius: "20px",
    fontSize: "0.85rem",
    fontWeight: "600",
    color: "white",
    marginTop: "10px",
  },
  cardTitle: {
    fontSize: "1.5rem",
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: "8px",
    display: "flex",
    alignItems: "center",
    gap: "10px",
  },
  cardSubtitle: {
    fontSize: "0.9rem",
    color: "#6b7280",
    marginBottom: "25px",
  },
  inputGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "flex",
    alignItems: "center",
    gap: "8px",
    fontSize: "0.9rem",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  inputWrapper: {
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    paddingLeft: "45px",
    border: "2px solid #e5e7eb",
    borderRadius: "12px",
    fontSize: "1rem",
    transition: "all 0.3s ease",
    outline: "none",
    fontFamily: "inherit",
    boxSizing: "border-box",
    background: "white",
  },
  inputIcon: {
    position: "absolute",
    left: "14px",
    color: "#9ca3af",
    pointerEvents: "none",
  },
  inputPassword: {
    paddingRight: "45px",
  },
  eyeButton: {
    position: "absolute",
    right: "12px",
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "6px",
    display: "flex",
    alignItems: "center",
    color: "#6b7280",
    transition: "color 0.2s ease",
  },
  button: {
    width: "100%",
    padding: "14px",
    background: "linear-gradient(135deg, #3b82f6 0%, #8b5cf6 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    fontSize: "1rem",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 8px 25px rgba(59, 130, 246, 0.4)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
  },
  infoGrid: {
    display: "grid",
    gap: "15px",
  },
  infoItem: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    padding: "16px",
    background: "#f9fafb",
    borderRadius: "12px",
    transition: "all 0.3s ease",
  },
  infoIconWrapper: {
    width: "40px",
    height: "40px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #3b82f6, #8b5cf6)",
    borderRadius: "10px",
    color: "white",
  },
  infoContent: {
    flex: 1,
  },
  infoLabel: {
    fontSize: "0.8rem",
    color: "#6b7280",
    fontWeight: "600",
    marginBottom: "2px",
  },
  infoValue: {
    fontSize: "0.95rem",
    color: "#1f2937",
    fontWeight: "600",
  },
  snackbar: {
    position: "fixed",
    top: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "16px 24px",
    borderRadius: "12px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.25)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    zIndex: 1000,
    minWidth: "320px",
    maxWidth: "90%",
    animation: "slideDown 0.4s ease",
  },
  snackbarSuccess: {
    background: "#10b981",
    color: "white",
  },
  snackbarError: {
    background: "#ef4444",
    color: "white",
  },
  closeBtn: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    padding: "4px",
    display: "flex",
    marginLeft: "auto",
  },
};
