export const styles = {
  pageWrapper: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    padding: "40px 20px",
    position: "relative",
    overflow: "hidden",
  },
  animatedBackground: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: `
      radial-gradient(circle at 20% 50%, rgba(120, 119, 198, 0.3), transparent 50%),
      radial-gradient(circle at 80% 80%, rgba(138, 43, 226, 0.3), transparent 50%),
      radial-gradient(circle at 40% 20%, rgba(102, 126, 234, 0.3), transparent 50%)
    `,
    animation: "pulse 15s ease-in-out infinite",
  },
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    position: "relative",
    zIndex: 1,
  },
  header: {
    textAlign: "center",
    marginBottom: "50px",
    animation: "fadeInDown 0.8s ease-out",
  },
  headerTitle: {
    fontSize: "clamp(2rem, 5vw, 3.5rem)",
    fontWeight: "800",
    color: "white",
    marginBottom: "15px",
    textShadow: "0 4px 20px rgba(0,0,0,0.2)",
  },
  headerSubtitle: {
    fontSize: "clamp(1rem, 2vw, 1.25rem)",
    color: "rgba(255,255,255,0.9)",
    marginBottom: "20px",
  },
  statusChip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "8px 16px",
    background: "rgba(255,255,255,0.2)",
    backdropFilter: "blur(10px)",
    borderRadius: "50px",
    color: "white",
    fontSize: "14px",
    fontWeight: "600",
    gap: "8px",
  },
  onlineDot: {
    width: "8px",
    height: "8px",
    background: "#4ade80",
    borderRadius: "50%",
    animation: "pulse 2s ease-in-out infinite",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(280px, 1fr))",
    gap: "24px",
    marginBottom: "40px",
  },
  quickActionCard: {
    background: "rgba(255,255,255,0.1)",
    backdropFilter: "blur(20px)",
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: "20px",
    padding: "30px",
    textAlign: "center",
    transition: "all 0.4s cubic-bezier(0.4, 0, 0.2, 1)",
    cursor: "pointer",
    animation: "fadeInUp 1s ease-out",
  },
  quickActionIcon: {
    width: "48px",
    height: "48px",
    margin: "0 auto 20px",
    color: "white",
    filter: "drop-shadow(0 4px 12px rgba(255,255,255,0.3))",
  },
  quickActionTitle: {
    fontSize: "1.25rem",
    fontWeight: "700",
    color: "white",
    marginBottom: "8px",
  },
  quickActionText: {
    fontSize: "0.95rem",
    color: "rgba(255,255,255,0.8)",
  },
  mainGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
    gap: "30px",
    marginTop: "30px",
  },
  card: {
    background: "rgba(255,255,255,0.95)",
    backdropFilter: "blur(20px)",
    borderRadius: "24px",
    padding: "40px",
    boxShadow: "0 20px 60px rgba(0,0,0,0.2)",
    animation: "fadeInUp 1.2s ease-out",
  },
  formTitle: {
    fontSize: "1.75rem",
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: "10px",
  },
  formSubtitle: {
    fontSize: "0.95rem",
    color: "#6b7280",
    marginBottom: "30px",
  },
  inputGroup: {
    marginBottom: "20px",
  },
  label: {
    display: "block",
    fontSize: "0.95rem",
    fontWeight: "600",
    color: "#374151",
    marginBottom: "8px",
  },
  input: {
    width: "100%",
    padding: "14px 16px",
    border: "2px solid #e5e7eb",
    borderRadius: "12px",
    fontSize: "1rem",
    transition: "all 0.3s ease",
    outline: "none",
    fontFamily: "inherit",
    boxSizing: "border-box",
  },
  textarea: {
    width: "100%",
    padding: "14px 16px",
    border: "2px solid #e5e7eb",
    borderRadius: "12px",
    fontSize: "1rem",
    transition: "all 0.3s ease",
    outline: "none",
    fontFamily: "inherit",
    resize: "vertical",
    minHeight: "140px",
    boxSizing: "border-box",
  },
  submitButton: {
    width: "100%",
    padding: "16px",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    color: "white",
    border: "none",
    borderRadius: "12px",
    fontSize: "1.05rem",
    fontWeight: "700",
    cursor: "pointer",
    transition: "all 0.3s ease",
    boxShadow: "0 10px 30px rgba(102, 126, 234, 0.4)",
  },
  faqTitle: {
    fontSize: "1.75rem",
    fontWeight: "700",
    color: "#1f2937",
    marginBottom: "25px",
  },
  accordion: {
    border: "none",
    marginBottom: "12px",
    borderRadius: "12px",
    overflow: "hidden",
    background: "#f9fafb",
    transition: "all 0.3s ease",
  },
  accordionHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "18px 20px",
    cursor: "pointer",
    background: "transparent",
    border: "none",
    width: "100%",
    textAlign: "left",
    transition: "all 0.3s ease",
  },
  faqQuestion: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flex: 1,
  },
  faqIconWrapper: {
    width: "36px",
    height: "36px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    borderRadius: "10px",
    color: "white",
  },
  faqQuestionText: {
    fontSize: "1rem",
    fontWeight: "600",
    color: "#1f2937",
  },
  chevron: {
    transition: "transform 0.3s ease",
    color: "#6b7280",
  },
  accordionContent: {
    padding: "0 20px 20px 68px",
    fontSize: "0.95rem",
    color: "#4b5563",
    lineHeight: "1.7",
    animation: "fadeIn 0.3s ease",
  },
  snackbar: {
    position: "fixed",
    top: "20px",
    left: "50%",
    transform: "translateX(-50%)",
    padding: "16px 24px",
    borderRadius: "12px",
    boxShadow: "0 10px 40px rgba(0,0,0,0.2)",
    display: "flex",
    alignItems: "center",
    gap: "12px",
    zIndex: 1000,
    minWidth: "320px",
    maxWidth: "90%",
    animation: "slideDown 0.3s ease",
  },
  snackbarSuccess: {
    background: "#10b981",
    color: "white",
  },
  snackbarError: {
    background: "#ef4444",
    color: "white",
  },
  closeButton: {
    background: "none",
    border: "none",
    color: "inherit",
    cursor: "pointer",
    padding: "4px",
    display: "flex",
    alignItems: "center",
    marginLeft: "auto",
  },
};